### ISSUE TITLE
It's so good

### ISSUE THREAD

**Issue by laosandegudai** [agentpowers/orleans-event-sourcing#13]
I found some commit,you add some exciting code.
as reconciler,why not create a reconcile basegrain instead of  additional grin to aggerate?

**Comment by agentpowers** [comment]
That grain is just for testing, logic is not complete yet.  Regarding the aggregate grain, the idea is to have state for reconciler grain and have that state using event sourcing.

**Comment by laosandegudai** [comment]
I think it's for ultimate consistency, and I'll keep an eye on it. Thank you for making such a wonderful work.
