### ISSUE TITLE
Grain State != null

### ISSUE THREAD

**Issue by laosandegudai** [agentpowers/orleans-event-sourcing#5]
Why?
![image](https://user-images.githubusercontent.com/17979159/83319406-c6965800-a270-11ea-9885-e8a8ba322306.png)
Orleans ，a wrong key will create a grain?

**Comment by agentpowers** [comment]
In current implementation it will.  I am thinking of making an update where consumer can opt in and decide if grain needs to be created if it does not exist.  
Another option is to use grain state to control this behavior. For example a boolean flag in grain state to indicate that it is not initialized, although this will initialize an aggregate within database.

**Comment by laosandegudai** [comment]
The grain is always there   in  Orleans,but it  will be  different  when you use aggerate .

**Comment by agentpowers** [comment]
I meant to say if aggregate needs to be created.  Edited above comment.

**Comment by laosandegudai** [comment]
Yes.I dont know How to do it well. I will keep an eye on you.
